### ISSUE TITLE
建议不用百度云

### ISSUE THREAD

**Issue by frankniubi** [naco-siren/GmGard_public_release#1]
你好，我建议你们不要使用百度云来下载，我可以提供直链。

**Comment by naco-siren** [comment]
@frankniubi 请问具体是怎么操作呢？可以留个qq号

**Comment by frankniubi** [comment]
我的QQ是4318174
QQ加入答案是admin@mcbar.cc

Naco Siren <notifications@github.com> 于2018年8月26日周日 上午11:51写道：
