### ISSUE TITLE
请问如何注册

### ISSUE THREAD

**Issue by baka-gourd** [naco-siren/GmGard_public_release#2]
excited！

**Comment by EngineerAD** [comment]
It's a mystery.

**Comment by ultragalaxy2018** [comment]
but if i wanna a loginning code,What should I do

**Comment by EngineerAD** [comment]
if you means to login, i mean to sign up, there's no way to do this exactly. And talking the topic is also an impolite behavior, you should like a ''gentleman'',to do what they always do.At the end, you will found the answer.

**Comment by Jooooooooker** [comment]
为什么注册一个账号这么难啊
